---
 - hosts: all
   gather_facts: yes
   ignore_errors: yes
   tasks:
    - name: Install python3 in RHEL machines
      when: ansible_os_family == "RedHat"
      yum:
        name: python3
        state: present
    - name: Install python3 in Ubuntu machines
      when: ansible_os_family == "Debian"
      apt:
        name: python3
        state: present