# Playbook using loops to create multiple users/groups
---
  - hosts: all
    gather_facts: no
    tasks:
      - name: Create several users through loop
        user:
          name: "{{ item.name }}"
          state: present
          groups: "{{ item.groups }}"
        loop:
          - { name: 'testuser1', groups: 'wheel' }
          - { name: 'testuser2', groups: 'oracle' }
          - { name: 'testuser3', groups: 'mysql' }

     
   
   
   

