---
  - hosts: all
    gather_facts: no
    tasks:
        - name: Ensures Selinux is set to enforcing mode
          lineinfile:
            path: /etc/selinux/config
            regexp: '^SELINUX='
            line: SELINUX=enforcing
          